export { buildDigest } from './digest'
export type { ContractDigest, ComponentDigest, PropDigest, SlotDigest } from './digest'
export { diffDigests, bumpVersion } from './diff'
export type { DiffResult, Change, ChangeKind, Severity } from './diff'
export { canonicalType, typesEqual } from './variance'
