import { readFile, writeFile } from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

// ─── Bake the calendar behavior core into an emittable string ─────────────────
// Reads the canonical, unit-tested `calendar.ts` and writes `calendarSource.generated.ts`
// exporting its source text as a constant, so the React (and future Vue/Angular)
// emitters can VENDOR the SAME core verbatim next to a generated DatePicker without
// the generator reaching the filesystem at emit time (it also runs in-browser in
// Studio). Single source of truth -> no cross-framework drift (proposal 0029 §6).
//
// This mirrors the `iconSvgs.generated.ts` vendoring precedent. Run after editing
// calendar.ts: `npm run gen:behavior-source`.

const HERE = path.dirname(fileURLToPath(import.meta.url))
const OUT = path.join(HERE, 'calendarSource.generated.ts')

// Each behavior core baked into an emittable string constant (proposal 0029).
const CORES: Array<{ file: string; constName: string; what: string }> = [
  { file: 'calendar.ts', constName: 'CALENDAR_CORE_SOURCE', what: 'DatePicker' },
  { file: 'timepicker.ts', constName: 'TIME_CORE_SOURCE', what: 'TimePicker' },
  { file: 'color.ts', constName: 'COLOR_CORE_SOURCE', what: 'ColorPicker' },
]

async function main() {
  const banner =
    '// GENERATED by `npm run gen:behavior-source` - do not edit by hand.\n' +
    '// The framework-agnostic behavior cores, baked as strings so emitters can vendor them\n' +
    '// verbatim next to a generated component (proposal 0029). Edit the source .ts, then regen.\n'
  const parts: string[] = [banner]
  for (const core of CORES) {
    const source = await readFile(path.join(HERE, core.file), 'utf8')
    parts.push(`\nexport const ${core.constName} = ${JSON.stringify(source)}`)
    console.log(`Baked ${core.file} -> ${core.constName} (${source.length} chars, ${core.what})`)
  }
  await writeFile(OUT, parts.join('\n') + '\n', 'utf8')
  console.log(`Wrote ${path.relative(process.cwd(), OUT)}`)
}

main().catch((err) => {
  console.error(err)
  process.exit(1)
})
